# Homework 7
## Austin Castelo

### 1)

The numpy.fft package defines the coefficents of the DFT for $k = 0, \ldots,N-1$ as

$c_k = \sum_{j=0}^{N-1} f_j \exp\left\{-2\pi i{jk \over N}\right\} \qquad k = 0,\ldots,N-1$

which is equation (1)

### 2)

The numpy.fft package defines the coefficents of the inverse DFT for $k = 0, \ldots,N-1$ as

$f_j = \frac{1}{N}\sum_{k=0}^{N-1}c_k\exp\left\{2\pi i{jk\over n}\right\} \qquad j = 0,\ldots,N-1.$

which is equation (2)

### 3)

$f_j \in \mathbb{R}$  $\forall j \in [0,1,\ldots,N-1]$

Prove $c_0$ is real and $c_{N-k} = \bar{c_k}$

$\textbf{Proof:}$

Must show $c_0 \in \mathbb{R}$

$c_k = \sum_{j=0}^{N-1} f_j \exp\left\{-2\pi i{jk \over N}\right\} \iff c_0 = \sum_{j=0}^{N-1} f_j \exp\left\{-2\pi i{j(0) \over N}\right\}$

$\iff c_0 = \sum_{j=0}^{N-1}f_j$

Since $f_j \in \mathbb{R}$  $\forall j \in [0,1,\ldots,N-1]$, $c_0 \in \mathbb{R}$

Must show $c_{N-k}= \bar{c_k}$

$c_{N-k}= \sum_{j=0}^{N-1}f_j\omega_N^{(N-k)j}$

Since $f_j$ are real numbers for $j\in[0,1,\ldots,N-1]$ it suffices to prove $\omega_N^{(N-k)j}=\bar{\omega}_N^{kj}$

Which is equivalent to proving $\omega_N^{(N-k)}=\bar{\omega}_N^k$

$\bar{\omega}_N^k = \exp\left\{i2\pi {k\over N}\right\}$

$\omega_N^{(N-k)} = \exp\left\{-i2\pi{N-k\over N}\right\} = \exp\left\{-i2\pi + i2\pi{k\over N}\right\}= \exp\left\{-i2\pi\right\}\exp\left\{i2\pi{k\over N}\right\} = \exp\left\{i2\pi{k\over N}\right\}$

Thus, $\omega_N^{(N-k)}=\bar{\omega}_N^k$, which implies $c_{N-k}= \bar{c_k}$

### 4)

$a_k = {2\over N} \sum_{j=0}^{N-1} f_j cos(kx_j)$ for $k=0,1,\ldots,{N\over 2}$

$ \iff a_k = {2\over N} \sum_{j=0}^{N-1} f_j{1\over 2}(\exp\left\{ikx_j\right\}+\exp\left\{-ikx_j\right\})$ 

$\iff {1\over N} \sum_{j=0}^{N-1} f_j(\exp\left\{ikj{2\pi \over N}\right\}+\exp\left\{-ikj{2\pi \over N}\right\})$ 

$\iff {1 \over N}(\bar{c}_k + c_k)$

$b_k = {2\over N} \sum_{j=0}^{N-1} f_j sin(kx_j)$ for $k=0,1,\ldots,{N\over 2}-1$

$\iff b_k = {2\over N} \sum_{j=0}^{N-1} f_j{1\over 2}(-i\exp\left\{ikx_j\right\}+ i\exp\left\{-ikx_j\right\})$ 

$\iff {i\over N} \sum_{j=0}^{N-1} f_j(-\exp\left\{ikx_j\right\}+ \exp\left\{-ikx_j\right\})$ 

$\iff {i\over N} \sum_{j=0}^{N-1} f_j(-\exp\left\{ikj{2\pi \over N}\right\}+ \exp\left\{-ikj{2\pi \over N}\right\})$

$\iff {i \over N}(- \bar{c}_k + c_k)$

### 5)

In [14]:
import numpy as np

f = [6.000000000000000,
     10.242640687119284,
     2.000000000000000,
     -2.585786437626905,
     2.000000000000000,
     1.757359312880716,
     -6.000000000000000,
     -5.414213562373098]
f=np.fft.fft(f)
f

array([8.00000000e+00 +0.j, 8.00000000e+00-16.j, 1.20000000e+01-20.j,
       3.10862447e-15 +0.j, 3.55271368e-15 +0.j, 3.10862447e-15 -0.j,
       1.20000000e+01+20.j, 8.00000000e+00+16.j])

$P_8(x)={a_0\over 2} + \sum_{k=1}^{{8\over2}-1}(a_kcos(kx)+b_ksin(kx))+{a_{8/2}\over 2}cos({8\over 2}x)$

$a_0 = {1\over 8}(\bar{c}_0 + c_0)= {(8+8)\over 8} = 2$

$a_1 = {(8+8)\over 8} = 2$

$b_1 = {i\over 8}(-\bar{c}_1 + c_1) = {i \over 8}(-(8+16i)+(8-16i))={i \over 8}(-32i)=4$

$a_2 = {(2*12)\over 8}=3$

$b_2 = {i \over 8}(-\bar{c}_2 + c_2) = {i \over 8}(-40i)=5$

$a_3 = {(2*3.10862447e-15)\over 8} = 7.771561175 × 10^-16$

$b_3 = {i \over 8}(-\bar{c}_3 + c_3) = {i \over 8}(0+0)=0$

$a_4 = {1\over 8}(\bar{c}_4 + c_4) = {(3.55271368e-15*2) \over 8}= 8.8817842 × 10^-16$

$P_8(x)={2\over 2} + \sum_{k=1}^{3}(a_kcos(kx)+b_ksin(kx))+{8.8817842 × 10^-16\over 2}cos({4}x)$

$P_8(x) = 1+ 2cos(x)+4sin(x)+3cos(2x)+5sin(2x)+7.771561175 × 10^{-16}cos(3x)+{8.8817842 × 10^{-16}\over 2}cos({4}x)$

### 6)

In [467]:
def f(x):
    return np.e**(np.sin(x))
def f_p(x):
    return(np.e**(np.sin(x))*np.cos(x))
def x(N):
    x = []
    for j in range(N):
        x.append(j*2*np.pi/N)
    return x
# This is an implementation of a Fourier 1st Derivative Polynomial interpolant of degree N
# Written by Austin Castelo
# 12/3/2018
# INPUT: value to interpolate x, list of values used for interpolation f, degree N, and DFT coefficents from FFT c
# OUPUT: interpolated derivative at point x P_n 
def P1(x,f,N, c):
    c = c/N
    i = complex(0,1)
    P_n = ((i*-int(N/2))*c[0]*(np.exp(-i*int(N/2)*x)))/2
    for k in range(-int(N/2)+1, int(N/2)):
        c_k = (i*k)*c[k]
        P_n += c_k*(np.exp(i*k*x))
    P_n += ((i*int(N/2))*c[0]*np.exp(i*int(N/2)*x))/2
    return P_n

In [468]:
x_n = x(8)
f_8 = f(x_n)
P_8 = []
c = np.fft.fft(f_8)
for i in x_n:
    P_8.append(P1(i,f_8,8, c))

In [469]:
P_8

[(0.9956820889014129+0j),
 (1.4375429562572408+0j),
 (1.8258810739490552e-15+0j),
 (-1.437542956257243+0j),
 (-0.995682088901411+0j),
 (-0.35138168662675706+0j),
 (3.657898842649997e-15+0j),
 (0.35138168662674935+0j)]

In [470]:
f_p8 = f_p(x_n)
f_p8

array([ 1.00000000e+00,  1.43409386e+00,  1.66446757e-16, -1.43409386e+00,
       -1.00000000e+00, -3.48652215e-01, -6.75783570e-17,  3.48652215e-01])

In [471]:
error = abs(f_p8-P_8)
error

array([4.31791110e-03, 3.44909971e-03, 1.65943432e-15, 3.44909971e-03,
       4.31791110e-03, 2.72947135e-03, 3.72547720e-15, 2.72947135e-03])

### 7)
#### a)

In [495]:
# This is an implementation of a Fourier 1st Derivative Polynomial interpolant of degree N using FFT and iFFT
# Written by Austin Castelo
# 12/4/2018
# INPUT: list of values from function to interpolate f and degree N
# OUPUT: list of interpolated derivatives at points f
def P1_2(f,N):
    c = np.fft.fft(f)
    i = complex(0,1)
    for k in range(-int(N/2)+1, int(N/2)):
        c[k] = (i*k)*c[k]
    f = np.fft.ifft(c)
    return f

In [496]:
P_1 = P1_2(f_8,8)
P_1

array([ 1.00115633+0.00000000e+00j,  1.43206872+3.19694302e-18j,
        0.00547424+0.00000000e+00j, -1.4430172 +3.19694302e-18j,
       -0.99020785+0.00000000e+00j, -0.35685593-3.19694302e-18j,
        0.00547424+0.00000000e+00j,  0.34590745-3.19694302e-18j])

#### b)

In [497]:
abs(P_1-P_8)

array([0.00547424, 0.00547424, 0.00547424, 0.00547424, 0.00547424,
       0.00547424, 0.00547424, 0.00547424])

#### c)

In [498]:
x_16 = x(16)
x_32 = x(32)
f_16 = f(x_16)
f_32 = f(x_32)
f_p16 = f_p(x_16)
f_p32 = f_p(x_32)
P_16 = P1_2(f_16,16)
P_32 = P1_2(f_32,32)
error_16 = abs(f_p16-P_16)
error_32 = abs(f_p32-P_32)

In [499]:
error_16

array([2.30231691e-08, 3.00067131e-08, 6.52540926e-08, 1.25019353e-07,
       1.99212481e-07, 2.73405608e-07, 3.33170869e-07, 3.68418249e-07,
       3.75401795e-07, 3.55993050e-07, 3.15552047e-07, 2.60913902e-07,
       1.99212480e-07, 1.37511058e-07, 8.28729130e-08, 4.24319119e-08])

In [500]:
error_32

array([1.55431223e-15, 8.88606824e-16, 2.22044605e-16, 4.44307609e-16,
       1.99852353e-15, 1.77647207e-15, 7.77451293e-16, 3.33525263e-16,
       1.08660296e-15, 1.22124534e-15, 1.55431223e-15, 1.99844927e-15,
       3.33074233e-15, 1.77636797e-15, 3.10866551e-15, 1.11024864e-15,
       2.66453526e-15, 4.44966113e-16, 3.33066907e-15, 1.05480385e-15,
       1.77649418e-15, 3.89121919e-16, 6.10998297e-16, 1.22136894e-15,
       1.13358045e-16, 1.80411318e-16, 8.32667268e-16, 5.27537155e-16,
       6.11022094e-16, 1.27677037e-15, 4.44376381e-16, 2.88658999e-15])