# Homework 4

## Austin Castelo

### 1) (a)

In [127]:
import numpy as np
def A_b(A,b):
    for i in range(len(A)):
        A[i].append(b[i])
    return A

def Gaus(A,b):
    L = []
    A = A_b(A,b)
    for i in range(len(A[0])-1):
        index = i
        m = A[i][i]
        for j in range(i,len(A)):
            if abs(A[j][i]) > abs(m):
                m = A[j][i]
                index = j
        if m == 0:
            return 'A is nonsingular'
        r = A[index]
        A[index] = A[i]
        A[i] = r
        Lᵢ = []
        for n in range(len(A)):  
            if n < i:
                Lᵢ.append(0)
            else:    
                mult = A[n][i]/m
                Lᵢ.append(mult)
                for k in range(len(A[0])):
                    if mult != 1:
                        A[n][k] = A[n][k] - A[i][k]*mult
        L.append(Lᵢ)
    L = np.transpose(np.array(L))
    A = np.array(A)
    return [A,L]
def Back_sub(A,b):
    y = Gaus(A,b)
    U = y[0]
    L = y[1]
    x = np.zeros(len(U[0])-1)
    if U[-1][-2] == 0:
        return "A is nonsingular"
    x[-1] = U[-1][-1]/U[-1][-2]
    for i in range(2,len(U)+1):
        xᵢ = U[-i][-1]
        for j in range(len(U[0])-1):
            xᵢ -= U[-i][j]*x[j]
        if U[-i][-(i+1)] == 0:
            return "A is nonsingular"
        xᵢ = xᵢ/U[-i][-(i+1)]
        x[-i] = xᵢ
    return x,U,L

In [128]:
A = [[5,1,0,2,1],[0,4,0,1,2],[1,1,4,1,1],[0,1,2,6,0],[0,0,1,2,4]]
b = [1,2,3,4,5]

#### (b)

In [129]:
x = Back_sub(A,b)
x

(array([-0.17083787, -0.06746464,  0.46028292,  0.52448313,  0.8726877 ]),
 array([[ 5.        ,  1.        ,  0.        ,  2.        ,  1.        ,
          1.        ],
        [ 0.        ,  4.        ,  0.        ,  1.        ,  2.        ,
          2.        ],
        [ 0.        ,  0.        ,  4.        ,  0.4       ,  0.4       ,
          2.4       ],
        [ 0.        ,  0.        ,  0.        ,  5.55      , -0.7       ,
          2.3       ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  4.13963964,
          3.61261261]]),
 array([[1.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 1.        , 0.        , 0.        , 0.        ],
        [0.2       , 0.2       , 1.        , 0.        , 0.        ],
        [0.        , 0.25      , 0.5       , 1.        , 0.        ],
        [0.        , 0.        , 0.25      , 0.34234234, 1.        ]]))

#### (c)

In [100]:
A = [[5,1,0,2],[0,4,0,8],[1,1,4,2],[0,1,2,2]]
b = [1,2,3,4]

In [101]:
x = Back_sub(A,b)
x

'A is nonsingular'